package dinamica;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CargaDados {

	public static List<Funcionario> getListaFuncionarios() {
		List<Funcionario> funcionarios = new ArrayList<>();

        funcionarios.add(new Funcionario("João Silva", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9000")));
        funcionarios.add(new Funcionario("Maria Oliveira", DepartamentoEnum.RH, new BigDecimal("8000")));
        funcionarios.add(new Funcionario("Pedro Souza", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7000")));
        funcionarios.add(new Funcionario("Ana Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6000")));
        funcionarios.add(new Funcionario("José Lima", DepartamentoEnum.QUALIDADE, new BigDecimal("5500")));
        funcionarios.add(new Funcionario("Paula Rocha", DepartamentoEnum.VENDAS, new BigDecimal("7500")));
        funcionarios.add(new Funcionario("Carlos Alves", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9200")));
        funcionarios.add(new Funcionario("Fernanda Ribeiro", DepartamentoEnum.RH, new BigDecimal("8100")));
        funcionarios.add(new Funcionario("Lucas Fernandes", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7200")));
        funcionarios.add(new Funcionario("Juliana Costa", DepartamentoEnum.SUPORTE, new BigDecimal("6100")));
        funcionarios.add(new Funcionario("Ricardo Pereira", DepartamentoEnum.QUALIDADE, new BigDecimal("5600")));
        funcionarios.add(new Funcionario("Camila Lima", DepartamentoEnum.VENDAS, new BigDecimal("7600")));
        funcionarios.add(new Funcionario("Bruno Gomes", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9400")));
        funcionarios.add(new Funcionario("Patricia Ferreira", DepartamentoEnum.RH, new BigDecimal("8300")));
        funcionarios.add(new Funcionario("Marcelo Rodrigues", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7400")));
        funcionarios.add(new Funcionario("Renata Martins", DepartamentoEnum.SUPORTE, new BigDecimal("6200")));
        funcionarios.add(new Funcionario("Thiago Almeida", DepartamentoEnum.QUALIDADE, new BigDecimal("5700")));
        funcionarios.add(new Funcionario("Beatriz Araujo", DepartamentoEnum.VENDAS, new BigDecimal("7700")));
        funcionarios.add(new Funcionario("André Melo", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9600")));
        funcionarios.add(new Funcionario("Gabriela Cardoso", DepartamentoEnum.RH, new BigDecimal("8500")));
        funcionarios.add(new Funcionario("Marcos Silva", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7600")));
        funcionarios.add(new Funcionario("Letícia Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6300")));
        funcionarios.add(new Funcionario("Vinícius Lima", DepartamentoEnum.QUALIDADE, new BigDecimal("5800")));
        funcionarios.add(new Funcionario("Amanda Oliveira", DepartamentoEnum.VENDAS, new BigDecimal("7800")));
        funcionarios.add(new Funcionario("Felipe Almeida", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9800")));
        funcionarios.add(new Funcionario("Larissa Costa", DepartamentoEnum.RH, new BigDecimal("8700")));
        funcionarios.add(new Funcionario("Gustavo Ferreira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7700")));
        funcionarios.add(new Funcionario("Isabela Sousa", DepartamentoEnum.SUPORTE, new BigDecimal("6400")));
        funcionarios.add(new Funcionario("Renato Mendes", DepartamentoEnum.QUALIDADE, new BigDecimal("5900")));
        funcionarios.add(new Funcionario("Natália Correia", DepartamentoEnum.VENDAS, new BigDecimal("7900")));
        funcionarios.add(new Funcionario("Victor Ramos", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10000")));
        funcionarios.add(new Funcionario("Bianca Azevedo", DepartamentoEnum.RH, new BigDecimal("8900")));
        funcionarios.add(new Funcionario("Eduardo Barbosa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7800")));
        funcionarios.add(new Funcionario("Sofia Duarte", DepartamentoEnum.SUPORTE, new BigDecimal("6500")));
        funcionarios.add(new Funcionario("Leandro Pinto", DepartamentoEnum.QUALIDADE, new BigDecimal("6000")));
        funcionarios.add(new Funcionario("Tânia Gomes", DepartamentoEnum.VENDAS, new BigDecimal("8000")));
        funcionarios.add(new Funcionario("Rafael Campos", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10200")));
        funcionarios.add(new Funcionario("Carolina Martins", DepartamentoEnum.RH, new BigDecimal("9000")));
        funcionarios.add(new Funcionario("Diego Freitas", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7900")));
        funcionarios.add(new Funcionario("Elaine Teixeira", DepartamentoEnum.SUPORTE, new BigDecimal("6600")));
        funcionarios.add(new Funcionario("Rodrigo Rocha", DepartamentoEnum.QUALIDADE, new BigDecimal("6100")));
        funcionarios.add(new Funcionario("Vanessa Vieira", DepartamentoEnum.VENDAS, new BigDecimal("8100")));
        funcionarios.add(new Funcionario("Daniel Oliveira", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10400")));
        funcionarios.add(new Funcionario("Juliana Souza", DepartamentoEnum.RH, new BigDecimal("9200")));
        funcionarios.add(new Funcionario("Mateus Fernandes", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("8000")));
        funcionarios.add(new Funcionario("Tatiane Silva", DepartamentoEnum.SUPORTE, new BigDecimal("6700")));
        funcionarios.add(new Funcionario("Henrique Ribeiro", DepartamentoEnum.QUALIDADE, new BigDecimal("6200")));
        funcionarios.add(new Funcionario("Patrícia Lima", DepartamentoEnum.VENDAS, new BigDecimal("8200")));
        funcionarios.add(new Funcionario("Alexandre Santos", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10600")));
        funcionarios.add(new Funcionario("Mônica Costa", DepartamentoEnum.RH, new BigDecimal("9400")));
        funcionarios.add(new Funcionario("Fábio Almeida", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("8100")));
        funcionarios.add(new Funcionario("Jéssica Mendes", DepartamentoEnum.SUPORTE, new BigDecimal("6800")));
        funcionarios.add(new Funcionario("Rafael Pereira", DepartamentoEnum.QUALIDADE, new BigDecimal("6300")));
        funcionarios.add(new Funcionario("Karla Oliveira", DepartamentoEnum.VENDAS, new BigDecimal("8300")));
        funcionarios.add(new Funcionario("Thiago Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10800")));
        funcionarios.add(new Funcionario("Fernanda Rocha", DepartamentoEnum.RH, new BigDecimal("9600")));
        funcionarios.add(new Funcionario("Douglas Souza", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("8200")));
        funcionarios.add(new Funcionario("Aline Ribeiro", DepartamentoEnum.SUPORTE, new BigDecimal("6900")));
        funcionarios.add(new Funcionario("Guilherme Santos", DepartamentoEnum.QUALIDADE, new BigDecimal("6400")));
        funcionarios.add(new Funcionario("Tatiane Martins", DepartamentoEnum.VENDAS, new BigDecimal("8400")));
        funcionarios.add(new Funcionario("Lucas Martins", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9000")));
        funcionarios.add(new Funcionario("Amanda Costa", DepartamentoEnum.RH, new BigDecimal("8500")));
        funcionarios.add(new Funcionario("Felipe Rocha", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7000")));
        funcionarios.add(new Funcionario("Mariana Almeida", DepartamentoEnum.SUPORTE, new BigDecimal("6000")));
        funcionarios.add(new Funcionario("Daniel Carvalho", DepartamentoEnum.QUALIDADE, new BigDecimal("5500")));
        funcionarios.add(new Funcionario("Carla Ferreira", DepartamentoEnum.VENDAS, new BigDecimal("7500")));
        funcionarios.add(new Funcionario("Roberto Nascimento", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9200")));
        funcionarios.add(new Funcionario("Jessica Silva", DepartamentoEnum.RH, new BigDecimal("8600")));
        funcionarios.add(new Funcionario("Renato Lima", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7100")));
        funcionarios.add(new Funcionario("Gabriela Sousa", DepartamentoEnum.SUPORTE, new BigDecimal("6100")));
        funcionarios.add(new Funcionario("Marcelo Pereira", DepartamentoEnum.QUALIDADE, new BigDecimal("5600")));
        funcionarios.add(new Funcionario("Sabrina Mendes", DepartamentoEnum.VENDAS, new BigDecimal("7600")));
        funcionarios.add(new Funcionario("Alexandre Barbosa", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9400")));
        funcionarios.add(new Funcionario("Fernanda Santos", DepartamentoEnum.RH, new BigDecimal("8700")));
        funcionarios.add(new Funcionario("Thiago Moreira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7200")));
        funcionarios.add(new Funcionario("Patricia Oliveira", DepartamentoEnum.SUPORTE, new BigDecimal("6200")));
        funcionarios.add(new Funcionario("Gustavo Ribeiro", DepartamentoEnum.QUALIDADE, new BigDecimal("5700")));
        funcionarios.add(new Funcionario("Bruna Lima", DepartamentoEnum.VENDAS, new BigDecimal("7700")));
        funcionarios.add(new Funcionario("Carlos Araujo", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9600")));
        funcionarios.add(new Funcionario("Natalia Fernandes", DepartamentoEnum.RH, new BigDecimal("8800")));
        funcionarios.add(new Funcionario("Ricardo Silva", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7300")));
        funcionarios.add(new Funcionario("Juliana Costa", DepartamentoEnum.SUPORTE, new BigDecimal("6300")));
        funcionarios.add(new Funcionario("Anderson Gomes", DepartamentoEnum.QUALIDADE, new BigDecimal("5800")));
        funcionarios.add(new Funcionario("Camila Sousa", DepartamentoEnum.VENDAS, new BigDecimal("7800")));
        funcionarios.add(new Funcionario("Fabio Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9800")));
        funcionarios.add(new Funcionario("Aline Oliveira", DepartamentoEnum.RH, new BigDecimal("8900")));
        funcionarios.add(new Funcionario("Mateus Ribeiro", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7400")));
        funcionarios.add(new Funcionario("Larissa Silva", DepartamentoEnum.SUPORTE, new BigDecimal("6400")));
        funcionarios.add(new Funcionario("Vinicius Costa", DepartamentoEnum.QUALIDADE, new BigDecimal("5900")));
        funcionarios.add(new Funcionario("Luana Souza", DepartamentoEnum.VENDAS, new BigDecimal("7900")));
        funcionarios.add(new Funcionario("Marcos Pereira", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10000")));
        funcionarios.add(new Funcionario("Jessica Alves", DepartamentoEnum.RH, new BigDecimal("9000")));
        funcionarios.add(new Funcionario("Rodrigo Almeida", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7500")));
        funcionarios.add(new Funcionario("Bianca Ferreira", DepartamentoEnum.SUPORTE, new BigDecimal("6500")));
        funcionarios.add(new Funcionario("Guilherme Santos", DepartamentoEnum.QUALIDADE, new BigDecimal("6000")));
        funcionarios.add(new Funcionario("Tatiane Rocha", DepartamentoEnum.VENDAS, new BigDecimal("8000")));
        funcionarios.add(new Funcionario("Leandro Azevedo", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10200")));
        funcionarios.add(new Funcionario("Renata Martins", DepartamentoEnum.RH, new BigDecimal("9100")));
        funcionarios.add(new Funcionario("Diego Teixeira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7600")));
        funcionarios.add(new Funcionario("Elaine Lima", DepartamentoEnum.SUPORTE, new BigDecimal("6600")));
        funcionarios.add(new Funcionario("Rafael Oliveira", DepartamentoEnum.QUALIDADE, new BigDecimal("6100")));
        funcionarios.add(new Funcionario("Camila Silva", DepartamentoEnum.VENDAS, new BigDecimal("8100")));
        funcionarios.add(new Funcionario("Andre Costa", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10400")));
        funcionarios.add(new Funcionario("Juliana Mendes", DepartamentoEnum.RH, new BigDecimal("9200")));
        funcionarios.add(new Funcionario("Thiago Ferreira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7700")));
        funcionarios.add(new Funcionario("Gabriela Rocha", DepartamentoEnum.SUPORTE, new BigDecimal("6700")));
        funcionarios.add(new Funcionario("Felipe Souza", DepartamentoEnum.QUALIDADE, new BigDecimal("6200")));
        funcionarios.add(new Funcionario("Patricia Araujo", DepartamentoEnum.VENDAS, new BigDecimal("8200")));
        funcionarios.add(new Funcionario("Fernando Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10600")));
        funcionarios.add(new Funcionario("Mônica Costa", DepartamentoEnum.RH, new BigDecimal("9300")));
        funcionarios.add(new Funcionario("Fábio Ribeiro", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7800")));
        funcionarios.add(new Funcionario("Jessica Sousa", DepartamentoEnum.SUPORTE, new BigDecimal("6800")));
        funcionarios.add(new Funcionario("Gustavo Pereira", DepartamentoEnum.QUALIDADE, new BigDecimal("6300")));
        funcionarios.add(new Funcionario("Carla Martins", DepartamentoEnum.VENDAS, new BigDecimal("8300")));
        funcionarios.add(new Funcionario("Thiago Silva", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10800")));
        funcionarios.add(new Funcionario("Fernanda Almeida", DepartamentoEnum.RH, new BigDecimal("9400")));
        funcionarios.add(new Funcionario("Douglas Souza", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7900")));
        funcionarios.add(new Funcionario("Aline Ribeiro", DepartamentoEnum.SUPORTE, new BigDecimal("6900")));
        funcionarios.add(new Funcionario("Alberto Souza", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9050")));
        funcionarios.add(new Funcionario("Vera Cruz", DepartamentoEnum.RH, new BigDecimal("8550")));
        funcionarios.add(new Funcionario("Miguel Braga", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7050")));
        funcionarios.add(new Funcionario("Clara Batista", DepartamentoEnum.SUPORTE, new BigDecimal("6050")));
        funcionarios.add(new Funcionario("Rafaela Teixeira", DepartamentoEnum.QUALIDADE, new BigDecimal("5550")));
        funcionarios.add(new Funcionario("Eduardo Moura", DepartamentoEnum.VENDAS, new BigDecimal("7550")));
        funcionarios.add(new Funcionario("Jorge Pires", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9250")));
        funcionarios.add(new Funcionario("Cristiane Pinto", DepartamentoEnum.RH, new BigDecimal("8650")));
        funcionarios.add(new Funcionario("Helena Cardoso", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7150")));
        funcionarios.add(new Funcionario("Leonardo Gomes", DepartamentoEnum.SUPORTE, new BigDecimal("6150")));
        funcionarios.add(new Funcionario("Bruna Leal", DepartamentoEnum.QUALIDADE, new BigDecimal("5650")));
        funcionarios.add(new Funcionario("Sergio Carvalho", DepartamentoEnum.VENDAS, new BigDecimal("7650")));
        funcionarios.add(new Funcionario("Manuela Neves", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9450")));
        funcionarios.add(new Funcionario("Rodrigo Cruz", DepartamentoEnum.RH, new BigDecimal("8750")));
        funcionarios.add(new Funcionario("Aline Campos", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7250")));
        funcionarios.add(new Funcionario("Marcos Monteiro", DepartamentoEnum.SUPORTE, new BigDecimal("6250")));
        funcionarios.add(new Funcionario("Cecilia Rodrigues", DepartamentoEnum.QUALIDADE, new BigDecimal("5750")));
        funcionarios.add(new Funcionario("Fábio Vieira", DepartamentoEnum.VENDAS, new BigDecimal("7750")));
        funcionarios.add(new Funcionario("Lilian Silva", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9650")));
        funcionarios.add(new Funcionario("Roberta Duarte", DepartamentoEnum.RH, new BigDecimal("8850")));
        funcionarios.add(new Funcionario("Adriana Rocha", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7350")));
        funcionarios.add(new Funcionario("Mauro Reis", DepartamentoEnum.SUPORTE, new BigDecimal("6350")));
        funcionarios.add(new Funcionario("Bianca Ribeiro", DepartamentoEnum.QUALIDADE, new BigDecimal("5850")));
        funcionarios.add(new Funcionario("Gabriel Fonseca", DepartamentoEnum.VENDAS, new BigDecimal("7850")));
        funcionarios.add(new Funcionario("Marcelo Cardoso", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9850")));
        funcionarios.add(new Funcionario("Beatriz Andrade", DepartamentoEnum.RH, new BigDecimal("8950")));
        funcionarios.add(new Funcionario("Renato Correia", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7450")));
        funcionarios.add(new Funcionario("Vanessa Lima", DepartamentoEnum.SUPORTE, new BigDecimal("6450")));
        funcionarios.add(new Funcionario("Felipe Machado", DepartamentoEnum.QUALIDADE, new BigDecimal("5950")));
        funcionarios.add(new Funcionario("Simone Barbosa", DepartamentoEnum.VENDAS, new BigDecimal("7950")));
        funcionarios.add(new Funcionario("Lucas Alves", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10050")));
        funcionarios.add(new Funcionario("Débora Mendes", DepartamentoEnum.RH, new BigDecimal("9050")));
        funcionarios.add(new Funcionario("Fernando Nogueira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7550")));
        funcionarios.add(new Funcionario("Juliana Ferreira", DepartamentoEnum.SUPORTE, new BigDecimal("6550")));
        funcionarios.add(new Funcionario("Ricardo Santos", DepartamentoEnum.QUALIDADE, new BigDecimal("6050")));
        funcionarios.add(new Funcionario("Luciana Moura", DepartamentoEnum.VENDAS, new BigDecimal("8050")));
        funcionarios.add(new Funcionario("Carlos Pinto", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10250")));
        funcionarios.add(new Funcionario("Patrícia Castro", DepartamentoEnum.RH, new BigDecimal("9150")));
        funcionarios.add(new Funcionario("Gustavo Fernandes", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7650")));
        funcionarios.add(new Funcionario("Larissa Martins", DepartamentoEnum.SUPORTE, new BigDecimal("6650")));
        funcionarios.add(new Funcionario("Thiago Barbosa", DepartamentoEnum.QUALIDADE, new BigDecimal("6150")));
        funcionarios.add(new Funcionario("Daniele Costa", DepartamentoEnum.VENDAS, new BigDecimal("8150")));
        funcionarios.add(new Funcionario("Vitor Rocha", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10450")));
        funcionarios.add(new Funcionario("Renata Nunes", DepartamentoEnum.RH, new BigDecimal("9250")));
        funcionarios.add(new Funcionario("Rafael Sousa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7750")));
        funcionarios.add(new Funcionario("Tatiane Gomes", DepartamentoEnum.SUPORTE, new BigDecimal("6750")));
        funcionarios.add(new Funcionario("Amanda Dias", DepartamentoEnum.QUALIDADE, new BigDecimal("6250")));
        funcionarios.add(new Funcionario("Murilo Oliveira", DepartamentoEnum.VENDAS, new BigDecimal("8250")));
        funcionarios.add(new Funcionario("Joana Silva", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10650")));
        funcionarios.add(new Funcionario("Fabiana Santos", DepartamentoEnum.RH, new BigDecimal("9350")));
        funcionarios.add(new Funcionario("Otávio Lima", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7850")));
        funcionarios.add(new Funcionario("Isabela Costa", DepartamentoEnum.SUPORTE, new BigDecimal("6850")));
        funcionarios.add(new Funcionario("Nathalia Almeida", DepartamentoEnum.QUALIDADE, new BigDecimal("6350")));
        funcionarios.add(new Funcionario("Renan Oliveira", DepartamentoEnum.VENDAS, new BigDecimal("8350")));
        funcionarios.add(new Funcionario("Samuel Campos", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10850")));
        funcionarios.add(new Funcionario("Raquel Silva", DepartamentoEnum.RH, new BigDecimal("9450")));
        funcionarios.add(new Funcionario("Cesar Santos", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7950")));
        funcionarios.add(new Funcionario("Lívia Carvalho", DepartamentoEnum.SUPORTE, new BigDecimal("6950")));
        funcionarios.add(new Funcionario("Thiago da Silva Souza", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9050")));
        funcionarios.add(new Funcionario("Lucas Pereira Lima", DepartamentoEnum.RH, new BigDecimal("8550")));
        funcionarios.add(new Funcionario("Maria Oliveira Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7050")));
        funcionarios.add(new Funcionario("José Antonio Martins", DepartamentoEnum.SUPORTE, new BigDecimal("6050")));
        funcionarios.add(new Funcionario("Ana Clara Santos", DepartamentoEnum.QUALIDADE, new BigDecimal("5550")));
        funcionarios.add(new Funcionario("Paulo Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("7550")));
        funcionarios.add(new Funcionario("Fernanda Maria Pereira", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9250")));
        funcionarios.add(new Funcionario("Renato Augusto Lima", DepartamentoEnum.RH, new BigDecimal("8650")));
        funcionarios.add(new Funcionario("Gabriela Silva Oliveira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7150")));
        funcionarios.add(new Funcionario("Carlos Eduardo Costa", DepartamentoEnum.SUPORTE, new BigDecimal("6150")));
        funcionarios.add(new Funcionario("Luciana Santos Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("5650")));
        funcionarios.add(new Funcionario("Rodrigo José Souza", DepartamentoEnum.VENDAS, new BigDecimal("7650")));
        funcionarios.add(new Funcionario("Juliana Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9450")));
        funcionarios.add(new Funcionario("Marcelo Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("8750")));
        funcionarios.add(new Funcionario("Patrícia Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7250")));
        funcionarios.add(new Funcionario("Alexandre José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6250")));
        funcionarios.add(new Funcionario("Vanessa Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("5750")));
        funcionarios.add(new Funcionario("Marcos Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("7750")));
        funcionarios.add(new Funcionario("Isabela Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9650")));
        funcionarios.add(new Funcionario("Fernando Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("8850")));
        funcionarios.add(new Funcionario("Tatiana Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7350")));
        funcionarios.add(new Funcionario("Rafael José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6350")));
        funcionarios.add(new Funcionario("Laura Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("5850")));
        funcionarios.add(new Funcionario("Eduardo Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("7850")));
        funcionarios.add(new Funcionario("Júlia Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9850")));
        funcionarios.add(new Funcionario("Bruno Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("8950")));
        funcionarios.add(new Funcionario("Alessandra Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7450")));
        funcionarios.add(new Funcionario("Diego José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6450")));
        funcionarios.add(new Funcionario("Mariana Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("5950")));
        funcionarios.add(new Funcionario("André Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("7950")));
        funcionarios.add(new Funcionario("Camila Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10050")));
        funcionarios.add(new Funcionario("Leandro Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("9050")));
        funcionarios.add(new Funcionario("Suzana Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7550")));
        funcionarios.add(new Funcionario("Vítor José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6550")));
        funcionarios.add(new Funcionario("Roberta Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("6050")));
        funcionarios.add(new Funcionario("Otávio Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("8050")));
        funcionarios.add(new Funcionario("Flávia Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10250")));
        funcionarios.add(new Funcionario("Tiago Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("9150")));
        funcionarios.add(new Funcionario("Beatriz Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7650")));
        funcionarios.add(new Funcionario("Igor José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6650")));
        funcionarios.add(new Funcionario("Renata Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("6150")));
        funcionarios.add(new Funcionario("Leonardo Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("8150")));
        funcionarios.add(new Funcionario("Adriana Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10450")));
        funcionarios.add(new Funcionario("Aline Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("9250")));
        funcionarios.add(new Funcionario("Felipe Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7750")));
        funcionarios.add(new Funcionario("Simone José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6750")));
        funcionarios.add(new Funcionario("Cláudia Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("6250")));
        funcionarios.add(new Funcionario("Marcelo Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("8250")));
        funcionarios.add(new Funcionario("Érika Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10650")));
        funcionarios.add(new Funcionario("Fábio Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("9350")));
        funcionarios.add(new Funcionario("Carolina Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7850")));
        funcionarios.add(new Funcionario("Lucas José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6850")));
        funcionarios.add(new Funcionario("Viviane Silva Martins", DepartamentoEnum.QUALIDADE, new BigDecimal("6350")));
        funcionarios.add(new Funcionario("Gustavo Henrique Souza", DepartamentoEnum.VENDAS, new BigDecimal("8350")));
        funcionarios.add(new Funcionario("Maurício Pereira Lima", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10850")));
        funcionarios.add(new Funcionario("Letícia Antônio Oliveira", DepartamentoEnum.RH, new BigDecimal("9450")));
        funcionarios.add(new Funcionario("Rogério Maria Costa", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7950")));
        funcionarios.add(new Funcionario("Daniela José Santos", DepartamentoEnum.SUPORTE, new BigDecimal("6950")));
        funcionarios.add(new Funcionario("Ana Maria Rossi", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9350.50")));
        funcionarios.add(new Funcionario("Bruno Carlos Müller", DepartamentoEnum.RH, new BigDecimal("8550.75")));
        funcionarios.add(new Funcionario("Carlos Eduardo Garcia", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7050.20")));
        funcionarios.add(new Funcionario("Diana Maria Schmidt", DepartamentoEnum.SUPORTE, new BigDecimal("6050.30")));
        funcionarios.add(new Funcionario("Enzo Gabriel Fernandez", DepartamentoEnum.QUALIDADE, new BigDecimal("5550.45")));
        funcionarios.add(new Funcionario("Fernanda Helena Ortega", DepartamentoEnum.VENDAS, new BigDecimal("7550.80")));
        funcionarios.add(new Funcionario("Giovanni Luiz Fontana", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9250.60")));
        funcionarios.add(new Funcionario("Heloísa Beatriz Ricci", DepartamentoEnum.RH, new BigDecimal("8650.90")));
        funcionarios.add(new Funcionario("Isabela Sophie Kramer", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7150.10")));
        funcionarios.add(new Funcionario("José Antônio Lopez", DepartamentoEnum.SUPORTE, new BigDecimal("6150.50")));
        funcionarios.add(new Funcionario("Katia Mariana Beraldi", DepartamentoEnum.QUALIDADE, new BigDecimal("5650.70")));
        funcionarios.add(new Funcionario("Luiz Felipe Ortega", DepartamentoEnum.VENDAS, new BigDecimal("7650.65")));
        funcionarios.add(new Funcionario("Mariana Laura Weber", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9450.40")));
        funcionarios.add(new Funcionario("Nina Clara Lombardi", DepartamentoEnum.RH, new BigDecimal("8750.85")));
        funcionarios.add(new Funcionario("Otávio Cesar Gomez", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7250.55")));
        funcionarios.add(new Funcionario("Paula Adriana Carvalho", DepartamentoEnum.SUPORTE, new BigDecimal("6250.25")));
        funcionarios.add(new Funcionario("Quentin Eduardo Klein", DepartamentoEnum.QUALIDADE, new BigDecimal("5750.35")));
        funcionarios.add(new Funcionario("Rafael Tomás Mendez", DepartamentoEnum.VENDAS, new BigDecimal("7750.95")));
        funcionarios.add(new Funcionario("Sofia Luiza Santoro", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9650.75")));
        funcionarios.add(new Funcionario("Thiago Ricardo Zapata", DepartamentoEnum.RH, new BigDecimal("8850.20")));
        funcionarios.add(new Funcionario("Ursula Maria Duarte", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7350.15")));
        funcionarios.add(new Funcionario("Valentina Marta Lacerda", DepartamentoEnum.SUPORTE, new BigDecimal("6350.45")));
        funcionarios.add(new Funcionario("Wagner Luiz Monteiro", DepartamentoEnum.QUALIDADE, new BigDecimal("5850.60")));
        funcionarios.add(new Funcionario("Xavier Fernando Zanon", DepartamentoEnum.VENDAS, new BigDecimal("7850.30")));
        funcionarios.add(new Funcionario("Yasmin Helena Pacheco", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9850.10")));
        funcionarios.add(new Funcionario("Zeca Ricardo Fernandes", DepartamentoEnum.RH, new BigDecimal("8950.55")));
        funcionarios.add(new Funcionario("Alessandra Natalia Mastrangelo", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7450.25")));
        funcionarios.add(new Funcionario("Bárbara Clara Lima", DepartamentoEnum.SUPORTE, new BigDecimal("6450.70")));
        funcionarios.add(new Funcionario("César Miguel Bastos", DepartamentoEnum.QUALIDADE, new BigDecimal("5950.35")));
        funcionarios.add(new Funcionario("Davi Augusto Dias", DepartamentoEnum.VENDAS, new BigDecimal("7950.85")));
        funcionarios.add(new Funcionario("Elisa Sofia Domingues", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10050.50")));
        funcionarios.add(new Funcionario("Felipe Mariano Souza", DepartamentoEnum.RH, new BigDecimal("9050.75")));
        funcionarios.add(new Funcionario("Gustavo Bruno Nogueira", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7550.45")));
        funcionarios.add(new Funcionario("Helena Isabel Andrade", DepartamentoEnum.SUPORTE, new BigDecimal("6550.80")));
        funcionarios.add(new Funcionario("Isis Joana Correa", DepartamentoEnum.QUALIDADE, new BigDecimal("6050.65")));
        funcionarios.add(new Funcionario("Júlio César Bittencourt", DepartamentoEnum.VENDAS, new BigDecimal("8050.30")));
        funcionarios.add(new Funcionario("Karina Helena Neves", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10250.40")));
        funcionarios.add(new Funcionario("Leonardo André Castro", DepartamentoEnum.RH, new BigDecimal("9150.90")));
        funcionarios.add(new Funcionario("Matheus Luis Amaral", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7650.10")));
        funcionarios.add(new Funcionario("Nathalia Bianca Vargas", DepartamentoEnum.SUPORTE, new BigDecimal("6650.20")));
        funcionarios.add(new Funcionario("Otto Felipe Duarte", DepartamentoEnum.QUALIDADE, new BigDecimal("6150.35")));
        funcionarios.add(new Funcionario("Pedro Vinícius Oliveira", DepartamentoEnum.VENDAS, new BigDecimal("8150.45")));
        funcionarios.add(new Funcionario("Quintino Victor Torres", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10450.60")));
        funcionarios.add(new Funcionario("Regina Sofia Martins", DepartamentoEnum.RH, new BigDecimal("9250.75")));
        funcionarios.add(new Funcionario("Sara Vitória Almeida", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7750.85")));
        funcionarios.add(new Funcionario("Tadeu João Moreira", DepartamentoEnum.SUPORTE, new BigDecimal("6750.95")));
        funcionarios.add(new Funcionario("Urbano Henrique Farias", DepartamentoEnum.QUALIDADE, new BigDecimal("6250.40")));
        funcionarios.add(new Funcionario("Vicente Luiz Rocha", DepartamentoEnum.VENDAS, new BigDecimal("8250.25")));
        funcionarios.add(new Funcionario("William Bruno Costa", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10650.10")));
        funcionarios.add(new Funcionario("Ximena Isabel Ramos", DepartamentoEnum.RH, new BigDecimal("9350.80")));
        funcionarios.add(new Funcionario("Yara Helena Azevedo", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7850.20")));
        funcionarios.add(new Funcionario("Zoraide Maria Pires", DepartamentoEnum.SUPORTE, new BigDecimal("6850.35")));
        funcionarios.add(new Funcionario("Arthur Rafael Campos", DepartamentoEnum.QUALIDADE, new BigDecimal("6350.55")));
        funcionarios.add(new Funcionario("Bianca Sofia Tavares", DepartamentoEnum.VENDAS, new BigDecimal("8350.90")));
        funcionarios.add(new Funcionario("Carlos Eduardo Araújo", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10850.50")));
        funcionarios.add(new Funcionario("Diana Helena Carvalho", DepartamentoEnum.RH, new BigDecimal("9450.15")));
        funcionarios.add(new Funcionario("Enrico João Barreto", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7950.25")));
        funcionarios.add(new Funcionario("Fernanda Beatriz Prado", DepartamentoEnum.SUPORTE, new BigDecimal("6950.75")));
        funcionarios.add(new Funcionario("Bruno Akira Tanaka", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9350.50")));
        funcionarios.add(new Funcionario("Carlos Ivanov Petrov", DepartamentoEnum.RH, new BigDecimal("8550.75")));
        funcionarios.add(new Funcionario("Diana Yumiko Sato", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7050.20")));
        funcionarios.add(new Funcionario("Elena Sergei Volkov", DepartamentoEnum.SUPORTE, new BigDecimal("6050.30")));
        funcionarios.add(new Funcionario("Fábio Hiroshi Nakamura", DepartamentoEnum.QUALIDADE, new BigDecimal("5550.45")));
        funcionarios.add(new Funcionario("Gustavo Boris Romanov", DepartamentoEnum.VENDAS, new BigDecimal("7550.80")));
        funcionarios.add(new Funcionario("Helena Masaru Fujita", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9250.60")));
        funcionarios.add(new Funcionario("Isabela Vladimir Popov", DepartamentoEnum.RH, new BigDecimal("8650.90")));
        funcionarios.add(new Funcionario("João Taro Yamamoto", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7150.10")));
        funcionarios.add(new Funcionario("Larissa Ivan Ivanov", DepartamentoEnum.SUPORTE, new BigDecimal("6150.50")));
        funcionarios.add(new Funcionario("Márcia Yuki Suzuki", DepartamentoEnum.QUALIDADE, new BigDecimal("5650.70")));
        funcionarios.add(new Funcionario("Nicolas Dmitri Sokolov", DepartamentoEnum.VENDAS, new BigDecimal("7650.65")));
        funcionarios.add(new Funcionario("Otávio Yukio Okada", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9450.40")));
        funcionarios.add(new Funcionario("Paula Alexei Fedorov", DepartamentoEnum.RH, new BigDecimal("8750.85")));
        funcionarios.add(new Funcionario("Quintino Hiroshi Takahashi", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7250.55")));
        funcionarios.add(new Funcionario("Rafael Kirill Mikhailov", DepartamentoEnum.SUPORTE, new BigDecimal("6250.25")));
        funcionarios.add(new Funcionario("Sofia Masaru Tanaka", DepartamentoEnum.QUALIDADE, new BigDecimal("5750.35")));
        funcionarios.add(new Funcionario("Thiago Anatoly Smirnov", DepartamentoEnum.VENDAS, new BigDecimal("7750.95")));
        funcionarios.add(new Funcionario("Ursula Akio Mori", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9650.75")));
        funcionarios.add(new Funcionario("Victor Lev Vasiliev", DepartamentoEnum.RH, new BigDecimal("8850.20")));
        funcionarios.add(new Funcionario("Wagner Takashi Yamada", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7350.15")));
        funcionarios.add(new Funcionario("Xênia Nikolai Kuznetsov", DepartamentoEnum.SUPORTE, new BigDecimal("6350.45")));
        funcionarios.add(new Funcionario("Yara Katsuo Matsuda", DepartamentoEnum.QUALIDADE, new BigDecimal("5850.60")));
        funcionarios.add(new Funcionario("Zeca Timur Ivanov", DepartamentoEnum.VENDAS, new BigDecimal("7850.30")));
        funcionarios.add(new Funcionario("Aline Michiko Hashimoto", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("9850.10")));
        funcionarios.add(new Funcionario("Bruno Fyodor Orlov", DepartamentoEnum.RH, new BigDecimal("8950.55")));
        funcionarios.add(new Funcionario("Carlos Hiroshi Kojima", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7450.25")));
        funcionarios.add(new Funcionario("Diana Igor Mikhailov", DepartamentoEnum.SUPORTE, new BigDecimal("6450.70")));
        funcionarios.add(new Funcionario("Elena Satoshi Nakamura", DepartamentoEnum.QUALIDADE, new BigDecimal("5950.35")));
        funcionarios.add(new Funcionario("Fábio Leonid Gorbachev", DepartamentoEnum.VENDAS, new BigDecimal("7950.85")));
        funcionarios.add(new Funcionario("Gabriela Yuji Kimura", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10050.50")));
        funcionarios.add(new Funcionario("Hugo Alexei Volkov", DepartamentoEnum.RH, new BigDecimal("9050.75")));
        funcionarios.add(new Funcionario("Isabela Yusuke Watanabe", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7550.45")));
        funcionarios.add(new Funcionario("José Ivanovich Smirnov", DepartamentoEnum.SUPORTE, new BigDecimal("6550.80")));
        funcionarios.add(new Funcionario("Karen Seiji Nagata", DepartamentoEnum.QUALIDADE, new BigDecimal("6050.65")));
        funcionarios.add(new Funcionario("Leonardo Boris Petrov", DepartamentoEnum.VENDAS, new BigDecimal("8050.30")));
        funcionarios.add(new Funcionario("Marta Hiroshi Yamamoto", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10250.40")));
        funcionarios.add(new Funcionario("Nina Alexei Orlov", DepartamentoEnum.RH, new BigDecimal("9150.90")));
        funcionarios.add(new Funcionario("Oscar Yuto Takeda", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7650.10")));
        funcionarios.add(new Funcionario("Paulo Ivanov Kuznetsov", DepartamentoEnum.SUPORTE, new BigDecimal("6650.20")));
        funcionarios.add(new Funcionario("Quintino Masaru Sakai", DepartamentoEnum.QUALIDADE, new BigDecimal("6150.35")));
        funcionarios.add(new Funcionario("Roberta Timur Sokolov", DepartamentoEnum.VENDAS, new BigDecimal("8150.45")));
        funcionarios.add(new Funcionario("Sofia Dmitri Popov", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10450.60")));
        funcionarios.add(new Funcionario("Thiago Yusuke Suzuki", DepartamentoEnum.RH, new BigDecimal("9250.75")));
        funcionarios.add(new Funcionario("Ursula Alexei Petrov", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7750.85")));
        funcionarios.add(new Funcionario("Victor Leonid Volkov", DepartamentoEnum.SUPORTE, new BigDecimal("6750.95")));
        funcionarios.add(new Funcionario("Wagner Hiroshi Matsumoto", DepartamentoEnum.QUALIDADE, new BigDecimal("6250.40")));
        funcionarios.add(new Funcionario("Xênia Boris Romanov", DepartamentoEnum.VENDAS, new BigDecimal("8250.25")));
        funcionarios.add(new Funcionario("Yara Yusuke Takahashi", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10650.10")));
        funcionarios.add(new Funcionario("Zeca Anatoly Kuznetsov", DepartamentoEnum.RH, new BigDecimal("9350.80")));
        funcionarios.add(new Funcionario("Aline Taro Fujimoto", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7850.20")));
        funcionarios.add(new Funcionario("Bruno Igor Orlov", DepartamentoEnum.SUPORTE, new BigDecimal("6850.35")));
        funcionarios.add(new Funcionario("Carlos Seiji Yamashita", DepartamentoEnum.QUALIDADE, new BigDecimal("6350.55")));
        funcionarios.add(new Funcionario("Diana Alexei Popov", DepartamentoEnum.VENDAS, new BigDecimal("8350.90")));
        funcionarios.add(new Funcionario("Elena Yuto Watanabe", DepartamentoEnum.ADMINISTRACAO, new BigDecimal("10850.50")));
        funcionarios.add(new Funcionario("Fábio Dmitri Gorbachev", DepartamentoEnum.RH, new BigDecimal("9450.15")));
        funcionarios.add(new Funcionario("Gabriela Yuji Nakamura", DepartamentoEnum.DESENVOLVIMENTO, new BigDecimal("7950.25")));
        funcionarios.add(new Funcionario("Hugo Ivan Volkov", DepartamentoEnum.SUPORTE, new BigDecimal("6950.75")));

        
        return funcionarios;
	}
}
